import requests
from pprint import pprint

def evolution(ID):
    r = requests.get(f'https://pokeapi.co/api/v2/evolution-chain/{ID}/')
    print(r.status_code)
    response = r.json()
    começo = response['chain']
    # POKEMON INICIAL
    first_evolution = começo['species']['name']
    
    # PRIMEIRA EVOLUÇÃO
    if len(começo['evolves_to']) == 0:
        meio_evolution = ''
    elif len(começo['evolves_to']) > 1:
        meio_evolution = []
        total = len(começo['evolves_to'])
        for vezes in range(0, total):
            inicio = começo['evolves_to'][vezes]['species']['name'] 
            meio_evolution.append(inicio)
        return f"'{first_evolution}': {meio_evolution}, "
    elif len(começo['evolves_to']) == 1:
        meio_evolution = começo['evolves_to'][0]['species']['name']

    # SEGUNDA EVOLUÇÃO
    if len(começo['evolves_to']) == 0:
        
        evolution_finish = ''
    elif len(começo['evolves_to'][0]['evolves_to']) == 1:
        
        evolution_finish = começo['evolves_to'][0]['evolves_to'][0]['species']['name']
    else:
        evolution_finish = ''
    return f"'{first_evolution}': ['{meio_evolution}', '{evolution_finish}'], "


evolução = {
    'bulbasaur': ['ivysaur', 'venusaur'],
    'charmander': ['charmeleon', 'charizard'],
    'squirtle': ['wartortle', 'blastoise'],
    'caterpie': ['metapod', 'butterfree'],
    'weedle': ['kakuna', 'beedrill'],
    'pidgey': ['pidgeotto', 'pidgeot'],
    'rattata': ['raticate', ''],
    'spearow': ['fearow', ''],
    'ekans': ['arbok', ''],
    'pichu': ['pikachu', 'raichu'],
    'sandshrew': ['sandslash', ''],
    'nidoran-f': ['nidorina', 'nidoqueen'],
    'nidoran-m': ['nidorino', 'nidoking'],
    'cleffa': ['clefairy', 'clefable'],
    'vulpix': ['ninetales', ''],
    'igglybuff': ['jigglypuff', 'wigglytuff'],
    'zubat': ['golbat', 'crobat'],
    'oddish': ['gloom', ''],
    'paras': ['parasect', ''],
    'venonat': ['venomoth', ''],
    'diglett': ['dugtrio', ''],
    'meowth': ['persian', ''],
    'psyduck': ['golduck', ''],
    'mankey': ['primeape', ''],
    'growlithe': ['arcanine', ''], 
    'poliwag': ['poliwhirl', ('poliwrath', 'politoed')],
    'abra': ['kadabra', 'alakazam'],
    'machop': ['machoke', 'machamp'],
    'bellsprout': ['weepinbell', 'victreebel'],
    'tentacool': ['tentacruel', ''],
    'geodude': ['graveler', 'golem'],
    'ponyta': ['rapidash', ''],
    'slowpoke': ['slowbro', ''],
    'magnemite': ['magneton', 'magnezone'],
    'farfetchd': ['sirfetchd', ''],
    'doduo': ['dodrio', ''],
    'seel': ['dewgong', ''],
    'grimer': ['muk', ''],
    'shellder': ['cloyster', ''],
    'gastly': ['haunter', 'gengar'],
    'onix': ['steelix', ''],
    'drowzee': ['hypno', ''],
    'krabby': ['kingler', ''],
    'voltorb': ['electrode', ''],
    'exeggcute': ['exeggutor', ''],
    'cubone': ['marowak', ''],
    'tyrogue': ['hitmonlee', ''],
    'lickitung': ['lickilicky', ''],
    'koffing': ['weezing', ''],
    'rhyhorn': ['rhydon', 'rhyperior'],
    'happiny': ['chansey', 'blissey'],
    'tangela': ['tangrowth', ''],
    'kangaskhan': ['', ''],
    'horsea': ['seadra', 'kingdra'],
    'goldeen': ['seaking', ''],
    'staryu': ['starmie', ''],
    'mime-jr': ['mr-mime', 'mr-rime'],
    'scyther': ['scizor', ''],
    'smoochum': ['jynx', ''],
    'elekid': ['electabuzz', 'electivire'],
    'magby': ['magmar', 'magmortar'],
    'pinsir': ['', ''],
    'tauros': ['', ''],
    'magikarp': ['gyarados', ''],
    'lapras': ['', ''],
    'ditto': ['', ''],
    'eevee': ['vaporeon', 'jolteon', 'flareon', 'espeon', 'umbreon', 'leafeon', 'glaceon', 'sylveon'],
    'porygon': ['porygon2', 'porygon-z'],
    'omanyte': ['omastar', ''],
    'kabuto': ['kabutops', ''],
    'aerodactyl': ['', ''],
    'munchlax': ['snorlax', ''], 
    'articuno': ['', ''], 
    'zapdos': ['', ''], 
    'moltres': ['', ''], 
    'dratini': ['dragonair', 'dragonite'], 
    'mewtwo': ['', ''], 
    'mew': ['', ''], 
    'chikorita': ['bayleef', 'meganium'], 
    'cyndaquil': ['quilava', 'typhlosion'], 
    'totodile': ['croconaw', 'feraligatr'], 
    'sentret': ['furret', ''], 
    'hoothoot': ['noctowl', ''], 
    'ledyba': ['ledian', ''], 
    'spinarak': ['ariados', ''], 
    'chinchou': ['lanturn', ''], 
    'togepi': ['togetic', 'togekiss'], 
    'natu': ['xatu', ''], 
    'mareep': ['flaaffy', 'ampharos'], 
    'azurill': ['marill', 'azumarill'], 
    'bonsly': ['sudowoodo', ''], 
    'hoppip': ['skiploom', 'jumpluff'], 
    'aipom': ['ambipom', ''], 
    'sunkern': ['sunflora', ''], 
    'yanma': ['yanmega', ''], 
    'wooper': ['quagsire', ''], 
    'murkrow': ['honchkrow', ''], 
    'misdreavus': ['mismagius', ''], 
    'unown': ['', ''],
    'wynaut': ['wobbuffet', ''],
    'girafarig': ['', ''], 
    'pineco': ['forretress', ''], 
    'dunsparce': ['', ''], 
    'gligar': ['gliscor', ''], 
    'snubbull': ['granbull', ''], 
    'qwilfish': ['', ''], 
    'shuckle': ['', ''], 
    'heracross': ['', ''], 
    'sneasel': ['weavile', ''], 
    'teddiursa': ['ursaring', ''], 
    'slugma': ['magcargo', ''], 
    'swinub': ['piloswine', 'mamoswine'], 
    'corsola': ['cursola', ''], 
    'remoraid': ['octillery', ''], 
    'delibird': ['', ''], 
    'mantyke': ['mantine', ''], 
    'skarmory': ['', ''], 
    'houndour': ['houndoom', ''], 
    'phanpy': ['donphan', ''], 
    'stantler': ['', ''], 
    'smeargle': ['', ''], 
    'miltank': ['', ''], 
    'raikou': ['', ''], 
    'entei': ['', ''], 
    'suicune': ['', ''], 
    'larvitar': ['pupitar', 'tyranitar'], 
    'lugia': ['', ''], 
    'ho-oh': ['', ''], 
    'celebi': ['', ''], 
    'treecko': ['grovyle', 'sceptile'], 
    'torchic': ['combusken', 'blaziken'], 
    'mudkip': ['marshtomp', 'swampert'], 
    'poochyena': ['mightyena', ''], 
    'zigzagoon': ['linoone', 'obstagoon'], 
    'wurmple': ['silcoon', 'cascoon'], 
    'lotad': ['lombre', 'ludicolo'], 
    'seedot': ['nuzleaf', 'shiftry'], 
    'taillow': ['swellow', ''], 
    'wingull': ['pelipper', ''], 
    'ralts': ['kirlia', ''], 
    'surskit': ['masquerain', ''], 
    'shroomish': ['breloom', ''], 
    'slakoth': ['vigoroth', 'slaking'], 
    'nincada': ['ninjask', 'shedinja'], 
    'whismur': ['loudred', 'exploud'], 
    'makuhita': ['hariyama', ''], 
    'nosepass': ['probopass', ''], 
    'skitty': ['delcatty', ''], 
    'sableye': ['', ''], 
    'mawile': ['', ''], 
    'aron': ['lairon', 'aggron'], 
    'meditite': ['medicham', ''], 
    'electrike': ['manectric', ''], 
    'plusle': ['', ''], 
    'minun': ['', ''], 
    'volbeat': ['', ''], 
    'illumise': ['', ''], 
    'budew': ['roselia', 'roserade'], 
    'gulpin': ['swalot', ''], 
    'carvanha': ['sharpedo', ''], 
    'wailmer': ['wailord', ''], 
    'numel': ['camerupt', ''], 
    'torkoal': ['', ''], 
    'spoink': ['grumpig', ''], 
    'spinda': ['', ''], 
    'trapinch': ['vibrava', 'flygon'], 
    'cacnea': ['cacturne', ''], 
    'swablu': ['altaria', ''], 
    'zangoose': ['', ''], 
    'seviper': ['', ''], 
    'lunatone': ['', ''], 
    'solrock': ['', ''], 
    'barboach': ['whiscash', ''], 
    'corphish': ['crawdaunt', ''], 
    'baltoy': ['claydol', ''], 
    'lileep': ['cradily', ''], 
    'anorith': ['armaldo', ''], 
    'feebas': ['milotic', ''], 
    'castform': ['', ''], 
    'kecleon': ['', ''], 
    'shuppet': ['banette', ''], 
    'duskull': ['dusclops', 'dusknoir'], 
    'tropius': ['', ''], 
    'chingling': ['chimecho', ''], 
    'absol': ['', ''], 
    'snorunt': ['glalie', 'froslass'], 
    'spheal': ['sealeo', 'walrein'], 
    'clamperl': ['huntail', 'gorebyss'], 
    'relicanth': ['', ''], 
    'luvdisc': ['', ''], 
    'bagon': ['shelgon', 'salamence'], 
    'beldum': ['metang', 'metagross'], 
    'regirock': ['', ''], 
    'regice': ['', ''], 
    'registeel': ['', ''], 
    'latias': ['', ''], 
    'latios': ['', ''], 
    'kyogre': ['', ''], 
    'groudon': ['', ''],
    'rayquaza': ['', ''], 
    'jirachi': ['', ''], 
    'deoxys': ['', ''], 
    'turtwig': ['grotle', 'torterra'], 
    'chimchar': ['monferno', 'infernape'], 
    'piplup': ['prinplup', 'empoleon'], 
    'starly': ['staravia', 'staraptor'], 
    'bidoof': ['bibarel', ''], 
    'kricketot': ['kricketune', ''], 
    'cranidos': ['rampardos', ''],
    'shieldon': ['bastiodon', ''],
    'burmy': ['wormadam', 'mothim'],
    'combee': ['vespiquen', ''],
    'pachirisu': ['', ''],
    'buizel': ['floatzel', ''],
    'cherubi': ['cherrim', ''],
    'shellos': ['gastrodon', ''],
    'drifloon': ['drifblim', ''],
    'buneary': ['lopunny', ''],
    
}
'''
result = evolution(223)
print(result)
'''
lista = []
for p in range(211, 221):
    print(p)
    result = evolution(p)
    lista.append(result)
pprint(lista)
